
development:
  adapter: postgresql
  encoding: unicode
  database: splurty_development
  pool: 5
  username: postgres
  password: password
  host: localhost 



test:
  adapter: postgresql
  encoding: unicode
  database: splurty_test
  pool: 5
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: splurty_production
  pool: 5
  username: postgres
  password: password
  host: localhost
